config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
   resources :items, :only => [:create, :destroy]
  end
  
  #post 'items/create'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

# use :only to eliminate unneeded routes :only => [:some_index]
#priority is based on order of creation+ first created is highest priority

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(current_user.id)
    @item = Item.new
    @item.name = params[:item][:name]
    @item.user_id = @user.id
  
    if @item.save
      flash[:success] = "Task saved!"
      redirect_to user_path(@user.id)
  end
end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id])
    @item.destroy

    if @item.destroy
      flash[:success] = "Nice!! You knocked the #{@item.name} task off your list."
      redirect_to user_path(@user.id)
  end

    respond_to do |format|
      format.html
      format.js
    end
  end
end

# update_attribute method to update the created_at attribute on:
# Item.last.update(created_at: 9.days.ago)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="container-fluid">
<h3> Add Tasks </h3>

  <%= form_for [user, item] do |f| %>
    <form class="form-inline">
    <div class="form_group">
      <%= f.text_field :name, class: 'form-control' , placeholder: "Enter New Task", :required => 'required', autofocus: true %>
    </div>

    <div class="form group">
      <%= f.submit "Submit", class: 'btn btn-success' %>
     </div>
   </form> 
  <% end %>


app/views/items/_item.html.erb
<tbody id='item-<%= item.id %>'>
  <tr>
    <td><%= item.name %></td>
    <td class="text-right"><%= distance_of_time_in_words(item.created_at, Time.now)%> ago </td>
    <% if current_user.id == user.id %>
      <td class="text-center"><%= link_to "", user_item_path(user.id, item.id), method: :delete, class: 'glyphicon glyphicon-check ', remote: true %></td>
    <% end %>
  </tr>
</tbody>


app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlocItOff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
  <div class="navbar-header">
  <a class="navbar-brand">Blocitoff</a>
  </div>
    <ul class="nav nav-tabs">
      <li class="<%= 'active' if current_page?(welcome_index_path) %>"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
        <div class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li><%= link_to 'Hello, ' + current_user.email, welcome_index_path, :class => 'navbar-link' %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-cog"></span> Edit Profile'.html_safe, edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-log-out"></span> Sign Out'.html_safe, destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <% else %>
          <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log In'.html_safe, new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
       </div>
     </ul>
          <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
            </div>
            <br>
          <% elsif flash[:alert] %>
            <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
     <%= yield %>
   </div>
</body>
</html>

app/views/users/show.html.erb
<div class="container-fluid">
<div class="jumbotron">
  <h2> Let's Make That List, <%= @user.email %>!</h2>
    <% if current_user == nil %>
    <% elsif current_user.id == @user.id %>
  </div>
      <div class="container">
       <%= render partial: 'items/form', locals: { user: @user, item: @item } %>
    </div>  
  <% end %>
    <div class="container">
      <% if flash[:success] %>
        <p class="alert alert-success alert-autocloseable-success"><%= flash[:success] %></p>
      <% elsif flash[:alert] %>
        <p class="alert alert-danger alert-autocloseable-danger"><%= flash[:alert] %></p>
   <% end %>
</div>

<div class="container-fluid">
  <h3>Tasks that need completion:<h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th style="width:55%">Description</th>
          <th class="text-right">Created</th>
          <th class="text-center">Complete</th>
        </tr>
      </thead>
    <% @items.each do |item| %>
      <%= render partial: 'items/item', locals: {user: @user, item: item }%>
      <% end %>
    </table>
</div>
</div>

app/views/welcome/about.html.erb
<div class="jumbotron">
<h2>About This Application</h2>
<br>
<p>To-do lists are notorious for collecting junk: items that you want to remember, but are not 
very important and get put off consistently. To address the problem of to-do list clutter, we offer:</p> 

<h2>BlocItOff.</h2>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <div class="container-fluid">
    <div class="jumbotron">
      <h1> Welcome back,  <%= current_user.email %>!</h1>
        
        <p>Make a list, complete the task, or it self destructs!</p>
        <br>
        <h4><%= link_to 'Click here to get busy.', user_path(current_user.id),:class => "btn btn-info" %></h4>
  </div>
</div>
<% else %>
  <div class="container-fluid">
    <div class="jumbotron">
      <h1>BlocItOff</h1>
        <p>Create and manage to-do lists with explosive consequences.</p>
        <br>
        <%= link_to "Let's do this!", new_user_session_path, :class => 'navbar-link',:class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>